### ISSUE TITLE
error when use `SideOfTheWorld.fromDegrees()`

### ISSUE THREAD

**Issue by PackRuble** [PackRuble/weather_pack#5]
Stack error:
```text
Unhandled exception:
Invalid argument(s): contact the package author with this value - 0.0
#0      SideOfTheWorld.fromDegrees (package:weather_pack/src/utils/conversion.dart:203)
#1      _printCurrent (package:weather_in_console/weather_in_console.dart:274)
#2      _getWeather (package:weather_in_console/weather_in_console.dart:181)
<asynchronous suspension>
#3      getWeather (package:weather_in_console/weather_in_console.dart:30)
<asynchronous suspension>
```

**Comment by PackRuble** [comment]
the problem was solved in the release v.0.0.2
